In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('creditcard.csv')

In [4]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [6]:
df.shape

(284807, 31)

In [7]:
#df.isna().count()

In [8]:
100*sum(df['Class']==1)/sum(df['Class']==0)

0.17304750013189596

In [8]:
X = df.drop('Class',axis=1)

In [9]:
y = df['Class']

In [11]:
## Under Sampling

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
weight = dict({0:1,1:100})

In [14]:
rfc = RandomForestClassifier(class_weight=weight)

In [6]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [56]:
rfc.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [57]:
y_pred = rfc.predict(X_test)

In [58]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [64]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9996313331694814
[[56857     2]
 [   19    84]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56859
           1       0.98      0.82      0.89       103

    accuracy                           1.00     56962
   macro avg       0.99      0.91      0.94     56962
weighted avg       1.00      1.00      1.00     56962



In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.model_selection import KFold,GridSearchCV

In [31]:
log_class = LogisticRegression()
grid = {'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}
cv = KFold(n_splits=5,random_state=None,shuffle=False)

In [41]:
grid_model = GridSearchCV(estimator=log_class,param_grid=grid,cv=cv,n_jobs=-1,scoring='f1_macro')

In [42]:
grid_model.fit(X_train,y_train)

C:\Users\Vijay\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.81065348        nan 0.84721623        nan 0.82839177
        nan 0.83990792        nan 0.83532189]
  warnings.warn(
C:\Users\Vijay\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [43]:
y_pred = grid_model.predict(X_test)

In [45]:
print(confusion_matrix(y_test,y_pred))

[[56835    24]
 [   31    72]]


In [47]:
accuracy_score(y_test,y_pred)

0.9990344440153085

In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56859
           1       0.75      0.70      0.72       103

    accuracy                           1.00     56962
   macro avg       0.87      0.85      0.86     56962
weighted avg       1.00      1.00      1.00     56962



In [20]:
y_train.value_counts()

0    227456
1       389
Name: Class, dtype: int64

In [19]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns = NearMiss(0.8)
X_train_ns,y_train_ns = ns.fit_resample(X_train,y_train)
print('The no.of classes before fit {}'.format(Counter(y_train)))
print('The no.of classes after fit {}'.format(Counter(y_train_ns)))


C:\Users\Vijay\anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The no.of classes before fit Counter({0: 227456, 1: 389})
The no.of classes after fit Counter({0: 486, 1: 389})


In [29]:
rfc.fit(X_train_ns,y_train_ns)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [30]:
y_pred = rfc.predict(X_test)

In [33]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9793371019276008
[[55694  1165]
 [   12    91]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56859
           1       0.07      0.88      0.13       103

    accuracy                           0.98     56962
   macro avg       0.54      0.93      0.56     56962
weighted avg       1.00      0.98      0.99     56962



In [35]:
from imblearn.over_sampling import RandomOverSampler

In [36]:
os = RandomOverSampler(0.5)
X_train_ns,y_train_ns = os.fit_resample(X_train,y_train)
print('The no.of classes before fit {}'.format(Counter(y_train)))
print('The no.of classes after fit {}'.format(Counter(y_train_ns)))


C:\Users\Vijay\anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The no.of classes before fit Counter({0: 227456, 1: 389})
The no.of classes after fit Counter({0: 227456, 1: 113728})


In [37]:
rfc.fit(X_train_ns,y_train_ns)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [38]:
y_pred = rfc.predict(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9996137776061234
[[56856     3]
 [   19    84]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56859
           1       0.97      0.82      0.88       103

    accuracy                           1.00     56962
   macro avg       0.98      0.91      0.94     56962
weighted avg       1.00      1.00      1.00     56962



# SMOTETomek

In [11]:
from imblearn.combine import SMOTETomek

In [ ]:
os = SMOTETomek(0.75)
X_train_ns,y_train_ns = os.fit_resample(X_train,y_train)
print('The no.of classes before fit {}'.format(Counter(y_train)))
print('The no.of classes after fit {}'.format(Counter(y_train_ns)))

C:\Users\Vijay\anaconda3\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(
